### ISSUE TITLE
[connector.Discord] Handling connection interuptions

### ISSUE THREAD

**Issue by ph7vc** [ph7vc/Arcbot#24]
We have an issue where we cannot stop threads running from within themselves

Discord currently uses `messageConsumer` and `keepAlive` threads. Message consumer being the thread that handles data sent over the websocket, and the keep alive sending a data packet every x seconds to keep the connection alive

When killing the TCP connection to Discord; it should throw the `socket_error 104 connection reset by peer`. The issue is that this is being caught in the threads themselves by either reading or writing to the socket. 

How do we disconnect from the socket; join the threads and try connecting again?

**Comment by ph7vc** [comment]
tcpkill -i wlan0 port `lsof -i | grep python | grep -oE ':([0-9]+)' | sed 's/://'`

**Comment by ph7vc** [comment]
implemented by : 16f7b2596c27a14638cf68c1e567666ec198f436

**Comment by ph7vc** [comment]
Still need to handle case when `connect` does not give us back a socket connection

Perhaps it'll try several connection attempts?

**Comment by ZetaHunter** [comment]
My remote server constantly keeps dropping connection, need to fix this asap.

```
Exception in thread KeepAliveThread:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "connectors/Discord.py", line 176, in keepAlive
    self.writeSocket({"op":1,"d": time.time()})
  File "connectors/Discord.py", line 185, in writeSocket
    self.socket.send(json.dumps(data))
  File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 289, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 314, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python3.4/dist-packages/websocket/_core.py", line 472, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python3.4/dist-packages/websocket/_socket.py", line 109, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
```

**Comment by ph7vc** [comment]
The keep alive is supposed to well; keep the connection alive. I'm not sure why it would just randomly close like that; but you're right, we need to put in handling for the case when send has a closed connection

**Comment by ph7vc** [comment]
Handled in: 0cb464d95c2b879d553731ec8b947eb8af3cf17c
