### ISSUE TITLE
[core.Message] Race condition in plugin unloading

### ISSUE THREAD

**Issue by ph7vc** [ph7vc/Arcbot#45]
Trying to unload a plugin and this is what happend:

```
[02/07/2016 11:08:43] INFO     core.PluginManager        Unloaded plugin "Chance"

Exception in thread WorkerThread12:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/home/admin/Arcbot/core/ThreadPool.py", line 156, in run
    callable(*args, **kwargs)
  File "connectors/Discord.py", line 222, in __handleMessage
    self.core.command.checkMessage(message)
  File "/home/admin/Arcbot/core/Command.py", line 63, in checkMessage
    for key, command in self.commands.items():
RuntimeError: dictionary changed size during iteration
```

I believe this is being caused by the fact that the plugin is being unloaded whilst the command checking loop is still looking for other matches. 

Solutions?

1 . Could have the command loop queue up methods after it has completed its pass. 
2. Hold the state of the current commands registered in scope of the command checking loop

**Comment by ph7vc** [comment]
Fixed in: d1e2c93f93086fd4638a786d090e9f3a636e7c3

Dict's cannot be mutated during iteration. Solution was to create a seperate iterable object
